// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateMessage(arg1) {
  return window['go']['main']['App']['CreateMessage'](arg1);
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function Register(arg1, arg2) {
  return window['go']['main']['App']['Register'](arg1, arg2);
}

export function SetOverlayBackgroundMode(arg1) {
  return window['go']['main']['App']['SetOverlayBackgroundMode'](arg1);
}

export function SetOverlayInteractiveArea(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SetOverlayInteractiveArea'](arg1, arg2, arg3, arg4, arg5);
}

export function ShowGetMessage(arg1, arg2) {
  return window['go']['main']['App']['ShowGetMessage'](arg1, arg2);
}

export function ShowGetTitle(arg1, arg2) {
  return window['go']['main']['App']['ShowGetTitle'](arg1, arg2);
}
